-- Usuário para administração (execução de migrations)
CREATE USER app_admin WITH PASSWORD 'C*aYQMuDqK2nBJBakP#f';
GRANT CONNECT ON DATABASE "garius-storage" TO app_admin;
GRANT USAGE ON SCHEMA public TO app_admin;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO app_admin;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO app_admin;
ALTER DEFAULT PRIVILEGES FOR USER postgres IN SCHEMA public
GRANT ALL PRIVILEGES ON TABLES TO app_admin;
ALTER DEFAULT PRIVILEGES FOR USER postgres IN SCHEMA public
GRANT ALL PRIVILEGES ON SEQUENCES TO app_admin;

-- Usuário para produção (execução da API)
CREATE USER app_user WITH PASSWORD 'g2FEzaR@8$Vp5SfVN@GVS^1KQ5X&rX78s4DVzDJ&';
GRANT CONNECT ON DATABASE "garius-storage" TO app_user;
GRANT USAGE ON SCHEMA public TO app_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO app_user;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO app_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO app_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO app_user;